Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: erdison.dosti.test.handler.CreateUserHandler
      CodeUri: /home/erdi/Scrivania/test
      Runtime: java17
      Architectures:
        - x86_64