package erdison.dosti.test.DynamoDB.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
/**
 * A DynamoDB entity representing a user.
 * This class is used for mapping user data to a DynamoDB table.
 */
@DynamoDBTable(tableName = "test-users")
public class User {
    private String userId;
    private String username;
    private String email;

    /**
     * Get the user ID, which is generated as a DynamoDB hash key.
     *
     * @return The user ID.
     */
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getUserId() {
        return userId;
    }

    @DynamoDBAttribute
    public String getUsername() {
        return username;
    }

    @DynamoDBAttribute
    public String getEmail() {
        return email;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}



